### PR TITLE
Bump hashie version

### PR DESCRIPTION
**Pull request by radar**
Hello,

Tiny little change to bump hashie up to 1.0.0. This is the same version of hashie that the twitter gem depends on and it's the latest. hashie 0.1.3 was released in 'November 12, 2009', which was quite a while ago.

All the tests pass for me with this version bump, so I would consider it a Great Success. Perhaps even a Triumph.

### CODE REVIEW

**Comment by radar** [comment]
another commit, this time for the httparty version

**Comment by cldwalker** [comment]
+1, httparty is quite out of date

**Comment by radar** [comment]
As an alternative, I've found that https://github.com/grasshopperlabs/chargify_api_ares provides a cleaner API for Chargify.

**Comment by cldwalker** [comment]
@pengwynn any reason this can't be merged? We're having to use our fork in production because httparty is so stale

**Comment by cldwalker** [comment]
@radar merged in with 966c0dde0c434e33a9468f1e4511d0f64e4e0ed1

**Pull request closed without merging**
